In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('caesarian.csv')
df

Usia  Kelahiran_ke-  Waktu_Kelahiran  Tekanan_darah  Kelainan_jantung  \
0     22              1                0              2                 0   
1     26              2                0              1                 0   
2     26              2                1              1                 0   
3     28              1                0              2                 0   
4     22              2                0              1                 0   
..   ...            ...              ...            ...               ...   
75    27              2                1              1                 0   
76    33              4                0              1                 0   
77    29              2                1              2                 0   
78    25              1                2              0                 0   
79    24              2                2              1                 0   

    Caesarian  
0           0  
1           1  
2           0  
3           0  
4           1  
..        ...  
75          0  
76          1  
77          1  
78          1  
79          0  

[80 rows x 6 columns]

In [2]:
x = df.iloc[:, [0,1,2,3,4]].values
y = df.iloc[:, 5].values
x

array([[22,  1,  0,  2,  0],
       [26,  2,  0,  1,  0],
       [26,  2,  1,  1,  0],
       [28,  1,  0,  2,  0],
       [22,  2,  0,  1,  0],
       [26,  1,  1,  0,  0],
       [27,  2,  0,  1,  0],
       [32,  3,  0,  1,  0],
       [28,  2,  0,  1,  0],
       [27,  1,  1,  1,  0],
       [36,  1,  0,  1,  0],
       [33,  1,  1,  0,  0],
       [23,  1,  1,  1,  0],
       [20,  1,  0,  1,  1],
       [29,  1,  2,  0,  1],
       [25,  1,  2,  0,  0],
       [25,  1,  0,  1,  0],
       [20,  1,  2,  2,  0],
       [37,  3,  0,  1,  1],
       [24,  1,  2,  0,  1],
       [26,  1,  1,  1,  0],
       [33,  2,  0,  0,  1],
       [25,  1,  1,  2,  0],
       [27,  1,  0,  0,  1],
       [20,  1,  0,  2,  1],
       [18,  1,  0,  1,  0],
       [18,  1,  1,  2,  1],
       [30,  1,  0,  1,  0],
       [32,  1,  0,  2,  1],
       [26,  2,  1,  1,  1],
       [25,  1,  0,  0,  0],
       [40,  1,  0,  1,  1],
       [32,  2,  0,  2,  1],
       [27,  2,  0,  1,  1],
       [26,  2

In [3]:
y

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0], dtype=int64)

In [53]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)
x_train

array([[36,  1,  1,  2,  0],
       [31,  1,  0,  1,  0],
       [19,  1,  0,  1,  0],
       [24,  2,  2,  1,  0],
       [25,  2,  0,  1,  0],
       [20,  1,  2,  2,  0],
       [22,  1,  2,  2,  0],
       [32,  2,  0,  0,  0],
       [27,  2,  0,  1,  0],
       [32,  3,  1,  0,  1],
       [32,  3,  0,  1,  1],
       [22,  2,  0,  1,  0],
       [27,  2,  0,  1,  1],
       [35,  1,  1,  0,  0],
       [32,  1,  0,  2,  1],
       [33,  1,  1,  0,  0],
       [21,  1,  0,  0,  0],
       [27,  1,  0,  0,  1],
       [36,  1,  0,  1,  0],
       [40,  1,  0,  1,  1],
       [22,  1,  0,  1,  0],
       [19,  1,  0,  1,  0],
       [26,  2,  0,  1,  0],
       [32,  2,  0,  2,  1],
       [27,  2,  1,  1,  0],
       [29,  1,  2,  0,  1],
       [29,  2,  0,  1,  1],
       [24,  1,  2,  0,  1],
       [26,  2,  1,  1,  1],
       [29,  2,  0,  0,  1],
       [20,  1,  0,  2,  1],
       [28,  3,  0,  2,  0],
       [37,  3,  0,  1,  1],
       [22,  1,  0,  2,  0],
       [25,  1

In [54]:
y_train

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1], dtype=int64)

In [55]:
x_test

array([[33,  3,  2,  1,  1],
       [30,  1,  0,  1,  0],
       [25,  1,  0,  0,  0],
       [29,  2,  1,  2,  0],
       [28,  3,  0,  1,  1],
       [29,  1,  2,  0,  1],
       [28,  3,  0,  1,  0],
       [25,  1,  0,  0,  0],
       [26,  2,  2,  1,  0],
       [27,  2,  2,  0,  0],
       [27,  1,  0,  2,  1],
       [32,  2,  0,  1,  1],
       [26,  2,  1,  1,  0],
       [28,  2,  0,  1,  0],
       [30,  3,  2,  2,  0],
       [26,  2,  2,  1,  0],
       [28,  1,  0,  2,  0],
       [25,  1,  1,  2,  0],
       [32,  3,  0,  1,  0],
       [18,  1,  1,  2,  1]], dtype=int64)

In [56]:
y_test

array([0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1],
      dtype=int64)

In [57]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [58]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [59]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0],
      dtype=int64)

In [60]:
from sklearn.metrics import classification_report, confusion_matrix
print (classification_report(y_test, y_pred))
print (confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      0.90      0.78        10
           1       0.86      0.60      0.71        10

    accuracy                           0.75        20
   macro avg       0.77      0.75      0.74        20
weighted avg       0.77      0.75      0.74        20

[[9 1]
 [4 6]]


In [65]:
# prediksi 1 
# usia 25
# kelahiran 1
# waktu kelahiran sesuai hpl (0)
# tekanan darah normal (1)
# kelainan jantung tidak ada (0)

# prediksi 2
# usia 35
# kelahiran 1
# waktu kelahiran sesuai hpl (0)
# tekanan darah tinggi (2)
# kelainan jantung tidak ada (0)

data_prediksi = {'Usia': [25, 35],
                'Kelahiran': [1, 1],
                'Waktu_Kelahiran': [0, 0],
                'Tekanan_darah': [1, 2],
                'Kelainan_jantung': [0, 0],
                'Caesarian': ['NaN', 'NaN']}
df_prediksi = pd.DataFrame(data_prediksi)
df_prediksi

Usia  Kelahiran  Waktu_Kelahiran  Tekanan_darah  Kelainan_jantung Caesarian
0    25          1                0              1                 0       NaN
1    35          1                0              2                 0       NaN

In [80]:
x_prediksi = df_prediksi.iloc[:, [0, 1, 2, 3, 4]].values
x_prediksi

array([[25,  1,  0,  1,  0],
       [35,  1,  0,  2,  0]], dtype=int64)

In [72]:
# y_prediksi = classifier.predict(x_prediksi)
# y_prediksi

In [81]:
scaler.fit(x_prediksi)
x_prediksi = scaler.transform(x_prediksi)

In [82]:
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [83]:
y_prediksi = classifier.predict(x_prediksi)
y_prediksi

array([1, 1], dtype=int64)

In [84]:
hasil_prediksi = {'Usia': [25, 35],
                'Kelahiran': [1, 1],
                'Waktu_Kelahiran': [0, 0],
                'Tekanan_darah': [1, 2],
                'Kelainan_jantung': [0, 0],
                'Caesarian': y_prediksi}
df_hasil = pd.DataFrame(hasil_prediksi)
df_hasil

Usia  Kelahiran  Waktu_Kelahiran  Tekanan_darah  Kelainan_jantung  \
0    25          1                0              1                 0   
1    35          1                0              2                 0   

   Caesarian  
0          1  
1          1